# **Experiment Notebook**



## Context


### 0. Import Packages

In [260]:
! pip install -r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt

In [261]:
import pandas as pd
import numpy as np

In [262]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### 1.   Load Dataset

In [263]:
file_url = '/content/drive/MyDrive/Classroom/repurchase_dataset.csv'

In [264]:
df = pd.read_csv(file_url)

### 2. Explore Dataset

In [265]:
df.head()

ID  Target     age_band  gender car_model   car_segment  \
0   1       0  3. 35 to 44    Male   model_1           LCV   
1   2       0          NaN     NaN   model_2  Small/Medium   
2   3       0          NaN    Male   model_3     Large/SUV   
3   5       0          NaN     NaN   model_3     Large/SUV   
4   6       0          NaN  Female   model_2  Small/Medium   

   age_of_vehicle_years  sched_serv_warr  non_sched_serv_warr  \
0                     9                2                   10   
1                     6               10                    3   
2                     9               10                    9   
3                     5                8                    5   
4                     8                9                    4   

   sched_serv_paid  non_sched_serv_paid  total_paid_services  total_services  \
0                3                    7                    5               6   
1               10                    4                    9              10   
2               10                    9                   10              10   
3                8                    4                    5               6   
4               10                    7                    9               8   

   mth_since_last_serv  annualised_mileage  num_dealers_visited  \
0                    9                   8                   10   
1                    6                  10                    7   
2                    7                  10                    6   
3                    4                  10                    9   
4                    5                   4                    4   

   num_serv_dealer_purchased  
0                          4  
1                         10  
2                         10  
3                          7  
4                          9

In [266]:
df.shape

(131337, 17)

In [267]:
df.describe()

ID         Target  age_of_vehicle_years  sched_serv_warr  \
count  131337.000000  131337.000000         131337.000000    131337.000000   
mean    77097.384180       0.026809              5.493022         5.452500   
std     44501.636704       0.161525              2.843299         2.884328   
min         1.000000       0.000000              1.000000         1.000000   
25%     38563.000000       0.000000              3.000000         3.000000   
50%     77132.000000       0.000000              5.000000         5.000000   
75%    115668.000000       0.000000              8.000000         8.000000   
max    154139.000000       1.000000             10.000000        10.000000   

       non_sched_serv_warr  sched_serv_paid  non_sched_serv_paid  \
count        131337.000000    131337.000000        131337.000000   
mean              5.472517         5.452287             5.497050   
std               2.870665         2.886528             2.878699   
min               1.000000         1.000000             1.000000   
25%               3.000000         3.000000             3.000000   
50%               5.000000         5.000000             5.000000   
75%               8.000000         8.000000             8.000000   
max              10.000000        10.000000            10.000000   

       total_paid_services  total_services  mth_since_last_serv  \
count        131337.000000   131337.000000        131337.000000   
mean              5.481692        5.454967             5.469807   
std               2.880408        2.875961             2.859756   
min               1.000000        1.000000             1.000000   
25%               3.000000        3.000000             3.000000   
50%               5.000000        5.000000             5.000000   
75%               8.000000        8.000000             8.000000   
max              10.000000       10.000000            10.000000   

       annualised_mileage  num_dealers_visited  num_serv_dealer_purchased  
count       131337.000000        131337.000000              131337.000000  
mean             5.502836             5.485438                   5.480778  
std              2.854896             2.876772                   2.867524  
min              1.000000             1.000000                   1.000000  
25%              3.000000             3.000000                   3.000000  
50%              5.000000             5.000000                   5.000000  
75%              8.000000             8.000000                   8.000000  
max             10.000000            10.000000                  10.000000

### 3. Explore Target variable

In [268]:
target = 'Target'

In [269]:

df[target].head()


0    0
1    0
2    0
3    0
4    0
Name: Target, dtype: int64

In [270]:
df[target].describe()

count    131337.000000
mean          0.026809
std           0.161525
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Target, dtype: float64

In [271]:
df[target].unique()

array([0, 1])

In [272]:
df[target].isnull().sum()

0

### 4. Explore Variables of Interest

**Age of their last vehicle**

In [273]:

df["age_of_vehicle_years"].head()


0    9
1    6
2    9
3    5
4    8
Name: age_of_vehicle_years, dtype: int64

In [274]:
df["age_of_vehicle_years"].describe()

count    131337.000000
mean          5.493022
std           2.843299
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: age_of_vehicle_years, dtype: float64

In [275]:
df["age_of_vehicle_years"].unique()

array([ 9,  6,  5,  8,  7,  1,  3,  4, 10,  2])

In [276]:
df["age_of_vehicle_years"].isnull().sum()

0

**Number of scheduled services (e.g. regular check-ups) used under warranty**

In [277]:

df["sched_serv_warr"].head()


0     2
1    10
2    10
3     8
4     9
Name: sched_serv_warr, dtype: int64

In [278]:
df["sched_serv_warr"].describe()

count    131337.000000
mean          5.452500
std           2.884328
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: sched_serv_warr, dtype: float64

In [279]:
df["sched_serv_warr"].unique()

array([ 2, 10,  8,  9,  4,  1,  3,  7,  5,  6])

In [280]:
df["sched_serv_warr"].isnull().sum()

0

**Number of non-scheduled services (e.g. something broke out of the service cycle) used under warranty**

In [281]:

df["non_sched_serv_warr"].head()


0    10
1     3
2     9
3     5
4     4
Name: non_sched_serv_warr, dtype: int64

In [282]:
df["non_sched_serv_warr"].describe()

count    131337.000000
mean          5.472517
std           2.870665
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: non_sched_serv_warr, dtype: float64

In [283]:
df["non_sched_serv_warr"].unique()

array([10,  3,  9,  5,  4,  8,  1,  6,  2,  7])

In [284]:
df["non_sched_serv_warr"].isnull().sum()

0

**Amount paid for scheduled services**

In [285]:

df["sched_serv_paid"].head()


0     3
1    10
2    10
3     8
4    10
Name: sched_serv_paid, dtype: int64

In [286]:
df["sched_serv_paid"].describe()

count    131337.000000
mean          5.452287
std           2.886528
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: sched_serv_paid, dtype: float64

In [287]:
df["sched_serv_paid"].unique()

array([ 3, 10,  8,  5,  2,  6,  1,  4,  9,  7])

In [288]:
df["sched_serv_paid"].isnull().sum()

0

**Amount paid for non scheduled services**

In [289]:

df["non_sched_serv_paid"].head()


0    7
1    4
2    9
3    4
4    7
Name: non_sched_serv_paid, dtype: int64

In [290]:
df["non_sched_serv_paid"].describe()

count    131337.000000
mean          5.497050
std           2.878699
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: non_sched_serv_paid, dtype: float64

In [291]:
df["non_sched_serv_paid"].unique()

array([ 7,  4,  9,  3,  1,  2,  6,  5, 10,  8])

In [292]:
df["non_sched_serv_paid"].isnull().sum()

0

**Amount paid in total for services**

In [293]:

df["total_paid_services"].head()


0     5
1     9
2    10
3     5
4     9
Name: total_paid_services, dtype: int64

In [294]:
df["total_paid_services"].describe()

count    131337.000000
mean          5.481692
std           2.880408
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: total_paid_services, dtype: float64

In [295]:
df["total_paid_services"].unique()

array([ 5,  9, 10,  6,  8,  1,  2,  7,  3,  4])

In [296]:
df["total_paid_services"].isnull().sum()

0

**Total number of services**

In [297]:

df["total_services"].head()


0     6
1    10
2    10
3     6
4     8
Name: total_services, dtype: int64

In [298]:
df["total_services"].describe()

count    131337.000000
mean          5.454967
std           2.875961
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: total_services, dtype: float64

In [299]:
df["total_services"].unique()

array([ 6, 10,  8,  4,  2,  1,  3,  5,  9,  7])

In [300]:
df["total_services"].isnull().sum()

0

**The number of months since the last service**

In [301]:

df["mth_since_last_serv"].head()


0    9
1    6
2    7
3    4
4    5
Name: mth_since_last_serv, dtype: int64

In [302]:
df["mth_since_last_serv"].describe()

count    131337.000000
mean          5.469807
std           2.859756
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: mth_since_last_serv, dtype: float64

In [303]:
df["mth_since_last_serv"].unique()

array([ 9,  6,  7,  4,  5,  8,  1,  3, 10,  2])

In [304]:
df["mth_since_last_serv"].isnull().sum()

0

**Annualised vehicle mileage**

In [305]:

df["annualised_mileage"].head()


0     8
1    10
2    10
3    10
4     4
Name: annualised_mileage, dtype: int64

In [306]:
df["annualised_mileage"].describe()

count    131337.000000
mean          5.502836
std           2.854896
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: annualised_mileage, dtype: float64

In [307]:
df["annualised_mileage"].unique()

array([ 8, 10,  4,  5,  6,  1,  7,  3,  9,  2])

In [308]:
df["annualised_mileage"].isnull().sum()

0

**Number of different dealers visited for servicing**

In [309]:

df["num_dealers_visited"].head()


0    10
1     7
2     6
3     9
4     4
Name: num_dealers_visited, dtype: int64

In [310]:
df["num_dealers_visited"].describe()

count    131337.000000
mean          5.485438
std           2.876772
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: num_dealers_visited, dtype: float64

In [311]:
df["num_dealers_visited"].unique()

array([10,  7,  6,  9,  4,  5,  2,  1,  3,  8])

In [312]:
df["num_dealers_visited"].isnull().sum()

0

**Number of services had at the same dealer where the vehicle was purchased**

In [313]:

df["num_serv_dealer_purchased"].head()


0     4
1    10
2    10
3     7
4     9
Name: num_serv_dealer_purchased, dtype: int64

In [314]:
df["num_serv_dealer_purchased"].describe()

count    131337.000000
mean          5.480778
std           2.867524
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          10.000000
Name: num_serv_dealer_purchased, dtype: float64

In [315]:
df["num_serv_dealer_purchased"].unique()

array([ 4, 10,  7,  9,  8,  3,  1,  6,  2,  5])

In [316]:
df["num_serv_dealer_purchased"].isnull().sum()

0

**Age banded into categories**

In [317]:

df["age_band"].head()


0    3. 35 to 44
1            NaN
2            NaN
3            NaN
4            NaN
Name: age_band, dtype: object

In [318]:
df["age_band"].describe()

count           18962
unique              7
top       4. 45 to 54
freq             4058
Name: age_band, dtype: object

In [319]:
df["age_band"].unique()

array(['3. 35 to 44', nan, '1. <25', '4. 45 to 54', '2. 25 to 34',
       '7. 75+', '5. 55 to 64', '6. 65 to 74'], dtype=object)

In [320]:
df["age_band"].isnull().sum()

112375

**Gender**

In [321]:

df["gender"].head()


0      Male
1       NaN
2      Male
3       NaN
4    Female
Name: gender, dtype: object

In [322]:
df["gender"].describe()

count     62029
unique        2
top        Male
freq      36072
Name: gender, dtype: object

In [323]:
df["gender"].unique()

array(['Male', nan, 'Female'], dtype=object)

In [324]:
df["gender"].isnull().sum()

69308

**The model of vehicle**

In [325]:

df["car_model"].head()


0    model_1
1    model_2
2    model_3
3    model_3
4    model_2
Name: car_model, dtype: object

In [326]:
df["car_model"].describe()

count      131337
unique         19
top       model_2
freq        34491
Name: car_model, dtype: object

In [327]:
df["car_model"].unique()

array(['model_1', 'model_2', 'model_3', 'model_5', 'model_6', 'model_4',
       'model_7', 'model_8', 'model_9', 'model_10', 'model_11',
       'model_13', 'model_12', 'model_14', 'model_15', 'model_16',
       'model_17', 'model_18', 'model_19'], dtype=object)

In [328]:
df["car_model"].isnull().sum()

0

**The type of vehicle**

In [329]:

df["car_segment"].head()


0             LCV
1    Small/Medium
2       Large/SUV
3       Large/SUV
4    Small/Medium
Name: car_segment, dtype: object

In [330]:
df["car_segment"].describe()

count           131337
unique               4
top       Small/Medium
freq             54553
Name: car_segment, dtype: object

In [331]:
df["car_segment"].unique()

array(['LCV', 'Small/Medium', 'Large/SUV', 'Other'], dtype=object)

In [332]:
df["car_segment"].isnull().sum()

0

**Unique ID of the customer**

In [333]:

df["ID"].head()


0    1
1    2
2    3
3    5
4    6
Name: ID, dtype: int64

In [334]:
df["ID"].describe()

count    131337.000000
mean      77097.384180
std       44501.636704
min           1.000000
25%       38563.000000
50%       77132.000000
75%      115668.000000
max      154139.000000
Name: ID, dtype: float64

In [335]:
df["ID"].unique()

array([     1,      2,      3, ..., 154137, 154138, 154139])

In [336]:
df["ID"].isnull().sum()

0

### 5. Prepare Data

In [337]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [338]:
df_cleaned = df.copy()

**Cleaning NaN values**

In [339]:
df_cleaned =df_cleaned.dropna()

**One hot encode the categorical columns**

In [340]:
encoder = OneHotEncoder(sparse_output=False)

cat_cols = ['age_band', 'gender', 'car_model', 'car_segment']

encoded_features = encoder.fit_transform(df[cat_cols])

encoded_df = pd.DataFrame(encoded_features, columns=encoder.get_feature_names_out())


df_encoded = pd.concat([df_cleaned.drop(cat_cols, axis=1), encoded_df], axis=1)




/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

In [341]:
df_encoded.head()

ID  Target  age_of_vehicle_years  sched_serv_warr  non_sched_serv_warr  \
0    1.0     0.0                   9.0              2.0                 10.0   
6    8.0     0.0                   8.0              2.0                  8.0   
34  42.0     0.0                   5.0             10.0                  6.0   
38  46.0     0.0                   7.0              8.0                  2.0   
51  61.0     0.0                   6.0              4.0                  4.0   

    sched_serv_paid  non_sched_serv_paid  total_paid_services  total_services  \
0               3.0                  7.0                  5.0             6.0   
6               2.0                  9.0                  9.0             4.0   
34              9.0                  7.0                  8.0             9.0   
38              8.0                  2.0                  5.0             6.0   
51              4.0                  6.0                  5.0             4.0   

    mth_since_last_serv  ...  car_model_model_4  car_model_model_5  \
0                   9.0  ...                0.0                0.0   
6                   7.0  ...                0.0                0.0   
34                  8.0  ...                0.0                0.0   
38                  6.0  ...                0.0                0.0   
51                  8.0  ...                0.0                0.0   

    car_model_model_6  car_model_model_7  car_model_model_8  \
0                 0.0                0.0                0.0   
6                 0.0                0.0                0.0   
34                0.0                0.0                0.0   
38                0.0                0.0                0.0   
51                0.0                1.0                0.0   

    car_model_model_9  car_segment_LCV  car_segment_Large/SUV  \
0                 0.0              1.0                    0.0   
6                 0.0              0.0                    1.0   
34                0.0              0.0                    0.0   
38                0.0              0.0                    0.0   
51                0.0              1.0                    0.0   

    car_segment_Other  car_segment_Small/Medium  
0                 0.0                       0.0  
6                 0.0                       0.0  
34                0.0                       1.0  
38                0.0                       1.0  
51                0.0                       0.0  

[5 rows x 47 columns]

In [342]:
df_encoded.describe()

ID        Target  age_of_vehicle_years  sched_serv_warr  \
count   18306.000000  18306.000000          18306.000000     18306.000000   
mean    75934.698623      0.010598              7.481154         6.459412   
std     43878.669160      0.102401              1.904149         2.699402   
min         1.000000      0.000000              1.000000         1.000000   
25%     37738.750000      0.000000              6.000000         4.000000   
50%     75569.500000      0.000000              8.000000         7.000000   
75%    114360.500000      0.000000              9.000000         9.000000   
max    154042.000000      1.000000             10.000000        10.000000   

       non_sched_serv_warr  sched_serv_paid  non_sched_serv_paid  \
count         18306.000000     18306.000000         18306.000000   
mean              6.306238         6.585928             6.063094   
std               2.776449         2.681686             2.702029   
min               1.000000         1.000000             1.000000   
25%               4.000000         5.000000             4.000000   
50%               7.000000         7.000000             6.000000   
75%               9.000000         9.000000             8.000000   
max              10.000000        10.000000            10.000000   

       total_paid_services  total_services  mth_since_last_serv  ...  \
count         18306.000000    18306.000000         18306.000000  ...   
mean              6.396646        6.552770             6.783568  ...   
std               2.584227        2.626588             2.646943  ...   
min               1.000000        1.000000             1.000000  ...   
25%               4.000000        5.000000             5.000000  ...   
50%               7.000000        7.000000             7.000000  ...   
75%               9.000000        9.000000             9.000000  ...   
max              10.000000       10.000000            10.000000  ...   

       car_model_model_4  car_model_model_5  car_model_model_6  \
count      131337.000000      131337.000000      131337.000000   
mean            0.115390           0.187868           0.023383   
std             0.319493           0.390608           0.151116   
min             0.000000           0.000000           0.000000   
25%             0.000000           0.000000           0.000000   
50%             0.000000           0.000000           0.000000   
75%             0.000000           0.000000           0.000000   
max             1.000000           1.000000           1.000000   

       car_model_model_7  car_model_model_8  car_model_model_9  \
count      131337.000000      131337.000000      131337.000000   
mean            0.062184           0.049057           0.007568   
std             0.241490           0.215988           0.086667   
min             0.000000           0.000000           0.000000   
25%             0.000000           0.000000           0.000000   
50%             0.000000           0.000000           0.000000   
75%             0.000000           0.000000           0.000000   
max             1.000000           1.000000           1.000000   

       car_segment_LCV  car_segment_Large/SUV  car_segment_Other  \
count    131337.000000          131337.000000      131337.000000   
mean          0.187350               0.396842           0.000442   
std           0.390194               0.489245           0.021010   
min           0.000000               0.000000           0.000000   
25%           0.000000               0.000000           0.000000   
50%           0.000000               0.000000           0.000000   
75%           0.000000               1.000000           0.000000   
max           1.000000               1.000000           1.000000   

       car_segment_Small/Medium  
count             131337.000000  
mean                   0.415367  
std                    0.492787  
min                    0.000000  
25%                    0.000000  
50%                    0.000000  
75%                  

In [343]:
df_encoded = df_encoded.dropna()

### 6. Split Dataset

In [344]:
X = df_encoded.drop('Target', axis=1)
y = df_encoded['Target']

In [345]:
one_fifth = round(len(X) / 5)
one_fifth

3661

In [346]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.3, random_state=42)



In [347]:
y.isnull().sum()

0

In [348]:
y_train.isnull().sum()

0

In [349]:
y_train.value_counts()

Target
0.0    10145
1.0      105
Name: count, dtype: int64

### 7. Baseline Model

In [350]:
from sklearn.metrics import accuracy_score, f1_score

**Accuracy**

**Training Data**

In [351]:
y_mode = y.mode()

In [352]:
y_central = np.full(y_train.shape, y_mode)

In [353]:
train_perf= accuracy_score(y_train, y_central)

print(train_perf)

0.9897560975609756


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

**Validation Data**

In [354]:
y_central = np.full(y_val.shape, y_mode)

In [355]:
valid_perf= accuracy_score(y_val, y_central)

print(valid_perf)

0.9895311788802913


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

**Testing Data**

In [356]:
y_central = np.full(y_test.shape, y_mode)

In [357]:
test_perf = accuracy_score(y_test, y_central)

print(test_perf)

0.9882577826324412


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

**f1 Scores**

**Training Data**

In [358]:
y_central = np.full(y_train.shape, y_mode)

In [359]:
train_perf= f1_score(y_train, y_central, average='weighted')

print(train_perf)

0.9846605157887812


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

**Validation Data**

In [360]:
y_central = np.full(y_val.shape, y_mode)

In [361]:
valid_perf= f1_score(y_val, y_central, average='weighted')

print(valid_perf)

0.9843243115469015


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

**Testing Data**

In [362]:
y_central = np.full(y_test.shape, y_mode)

In [363]:
test_perf= f1_score(y_test, y_central, average='weighted')

print(test_perf)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

0.982421347437661


### Feature Scaling

In [364]:
from sklearn.preprocessing import StandardScaler

In [365]:
scaler = StandardScaler().set_output(transform="pandas")

In [366]:
scaler.fit(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


StandardScaler()

In [367]:
scaler.transform(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


ID  age_of_vehicle_years  sched_serv_warr  non_sched_serv_warr  \
55412  -0.240923              0.277899         0.194218            -1.188983   
67506   0.081605              0.277899        -0.918963             0.615440   
62063  -0.064022             -1.311351         0.194218            -1.188983   
103207  1.035123             -0.781601         0.565279            -1.910753   
11317  -1.421758             -0.251851        -0.176842            -0.828098   
...          ...                   ...              ...                  ...   
66531   0.055430             -0.781601        -1.290023            -0.828098   
105401  1.093347             -0.781601        -0.918963             0.615440   
14498  -1.336289              1.337399        -0.918963            -1.549868   
10528  -1.443176              0.277899         0.194218            -0.828098   
45878  -0.495759              1.337399        -0.176842             0.976325   

        sched_serv_paid  non_sched_serv_paid  total_paid_services  \
55412          0.890395            -1.133501            -0.157391   
67506          0.890395            -0.763100            -0.157391   
62063         -0.227461            -1.133501            -0.931319   
103207         0.890395            -1.133501            -0.157391   
11317          0.517776            -0.763100            -0.157391   
...                 ...                  ...                  ...   
66531         -0.972698            -0.763100            -1.318284   
105401        -0.972698             0.718507             0.229574   
14498         -0.227461            -1.503903            -0.931319   
10528          0.517776             0.348105             0.616538   
45878         -0.227461             1.459310             1.390467   

        total_services  mth_since_last_serv  annualised_mileage  ...  \
55412        -0.212519            -1.436102            0.232973  ...   
67506        -0.594746             0.458223            0.232973  ...   
62063        -0.594746             0.079358            1.002172  ...   
103207       -0.594746            -0.299507            0.232973  ...   
11317        -0.212519             0.079358            1.002172  ...   
...                ...                  ...                 ...  ...   
66531        -1.359202             1.215954           -1.305423  ...   
105401       -0.594746            -1.057237            0.617572  ...   
14498        -1.741430             1.215954           -0.920824  ...   
10528        -0.594746             0.837089            0.232973  ...   
45878         0.551937            -0.299507            0.617572  ...   

        car_model_model_4  car_model_model_5  car_model_model_6  \
55412           -0.397898          -0.461072          -0.163226   
67506           -0.397898          -0.461072          -0.163226   
62063           -0.397898          -0.461072          -0.163226   
103207          -0.397898          -0.461072          -0.163226   
11317           -0.397898          -0.461072          -0.163226   
...                   ...                ...                ...   
66531           -0.397898           2.168859          -0.163226   
105401          -0.397898          -0.461072          -0.163226   
14498            2.513206          -0.461072          -0.163226   
10528           -0.397898          -0.461072          -0.163226   
45878           -0.397898          -0.461072          -0.163226   

        car_model_model_7  car_model_model_8  car_model_model_9  \
55412            3.702146          -0.219952          -0.084108   
67506           -0.270114          -0.219952          -0.084108   
62063           -0.270114          -0.219952          -0.084108   
103207          -0.270114          -0.219952          -0.084108   
11317           -0.270114          -0.219952          -0.084108   
...                   ...                ...                ...   
66531           -0.270114          -0.219952          -0.084108   
105401          -0

In [368]:
X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasatt

### 8. Train Machine Learning Model

**For default Hyperparameter**

In [369]:
print(df_encoded['Target'].value_counts())

Target
0.0    18112
1.0      194
Name: count, dtype: int64


In [389]:
from sklearn.ensemble import ExtraTreesClassifier

In [390]:
model = ExtraTreesClassifier(random_state = 8)

In [391]:
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(

ExtraTreesClassifier(random_state=8)

**Hyperparamters tuning using Random Search**

In [393]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

In [394]:
random_dist = {
    'n_estimators': randint(50, 200),
    'min_samples_leaf': randint(1, 10),
    'max_depth': randint(3, 7),
    'max_features': randint(2, 6)
}
random_dist

{'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen at 0x7b1cbf71bb80>,
 'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen at 0x7b1cbf71a620>,
 'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen at 0x7b1cbf71a9e0>,
 'max_features': <scipy.stats._distn_infrastructure.rv_discrete_frozen at 0x7b1cbf718a90>}

In [395]:
assert isinstance(random_dist, dict)
assert random_dist.get('n_estimators') is not None
assert random_dist.get('min_samples_leaf') is not None
assert random_dist.get('max_depth') is not None
assert random_dist.get('max_features') is not None

In [396]:
et1 = ExtraTreesClassifier(random_state=8)

**Finding the best set of hypeparamters**

In [397]:
random_search_et = RandomizedSearchCV(et1, random_dist, random_state=8, scoring='neg_root_mean_squared_error', cv=5, verbose=1)

In [398]:
random_search_et.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

Fitting 5 folds for each of 10 candidates, totalling 50 fits


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(

RandomizedSearchCV(cv=5, estimator=ExtraTreesClassifier(random_state=8),
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7b1cbf71a9e0>,
                                        'max_features': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7b1cbf718a90>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7b1cbf71a620>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7b1cbf71bb80>},
                   random_state=8, scoring='neg_root_mean_squared_error',
                   verbose=1)

In [399]:
random_search_et.best_params_

{'max_depth': 6, 'max_features': 2, 'min_samples_leaf': 2, 'n_estimators': 155}

**Extracting the best model and saving it to another variable**

In [400]:
et2 = random_search_et.best_estimator_

In [418]:
et2 = ExtraTreesClassifier(max_depth=6, max_features=2, min_samples_leaf=2, n_estimators=155)


In [419]:
et2.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(

ExtraTreesClassifier(max_depth=6, max_features=2, min_samples_leaf=2,
                     n_estimators=155)

### Feature Importance

In [401]:
et2.feature_importances_

array([1.58843786e-01, 1.76924778e-01, 8.07465616e-02, 4.25756410e-02,
       8.34665961e-02, 1.60480881e-02, 3.82923203e-02, 7.70872271e-02,
       7.55949705e-02, 4.71243254e-02, 4.64633099e-02, 3.22507242e-02,
       4.05740762e-03, 4.96248252e-03, 2.59734445e-03, 4.60039401e-03,
       5.65031611e-03, 2.78411808e-03, 3.04846547e-03, 0.00000000e+00,
       8.62494307e-03, 6.51486441e-03, 0.00000000e+00, 3.65878522e-03,
       2.40391547e-04, 2.25714508e-04, 7.55278003e-06, 7.87415046e-03,
       2.60805754e-05, 2.64676465e-04, 9.17196144e-05, 8.22176259e-06,
       1.74799832e-05, 0.00000000e+00, 4.59235397e-03, 2.18697669e-02,
       1.87882723e-03, 7.91630277e-03, 1.32375181e-03, 1.75860499e-03,
       7.28656300e-03, 6.36758849e-04, 2.04109696e-03, 1.11189812e-02,
       2.72263278e-06, 8.90083249e-03])

In [402]:
feat_imp_et_df = pd.DataFrame(
    {
    'feature': X_train.columns,
     'feature_importance': et2.feature_importances_
     }
)

In [403]:
feat_imp_et_df

feature  feature_importance
0                          ID            0.158844
1        age_of_vehicle_years            0.176925
2             sched_serv_warr            0.080747
3         non_sched_serv_warr            0.042576
4             sched_serv_paid            0.083467
5         non_sched_serv_paid            0.016048
6         total_paid_services            0.038292
7              total_services            0.077087
8         mth_since_last_serv            0.075595
9          annualised_mileage            0.047124
10        num_dealers_visited            0.046463
11  num_serv_dealer_purchased            0.032251
12            age_band_1. <25            0.004057
13       age_band_2. 25 to 34            0.004962
14       age_band_3. 35 to 44            0.002597
15       age_band_4. 45 to 54            0.004600
16       age_band_5. 55 to 64            0.005650
17       age_band_6. 65 to 74            0.002784
18            age_band_7. 75+            0.003048
19               age_band_nan            0.000000
20              gender_Female            0.008625
21                gender_Male            0.006515
22                 gender_nan            0.000000
23          car_model_model_1            0.003659
24         car_model_model_10            0.000240
25         car_model_model_11            0.000226
26         car_model_model_12            0.000008
27         car_model_model_13            0.007874
28         car_model_model_14            0.000026
29         car_model_model_15            0.000265
30         car_model_model_16            0.000092
31         car_model_model_17            0.000008
32         car_model_model_18            0.000017
33         car_model_model_19            0.000000
34          car_model_model_2            0.004592
35          car_model_model_3            0.021870
36          car_model_model_4            0.001879
37          car_model_model_5            0.007916
38          car_model_model_6            0.001324
39          car_model_model_7            0.001759
40          car_model_model_8            0.007287
41          car_model_model_9            0.000637
42            car_segment_LCV            0.002041
43      car_segment_Large/SUV            0.011119
44          car_segment_Other            0.000003
45   car_segment_Small/Medium            0.008901

In [404]:
import altair as alt

In [405]:
alt.Chart(feat_imp_et_df).mark_bar().encode(
    x='feature_importance',
    y=alt.Y("feature", sort='-x'),
    tooltip=['feature','feature_importance'])

/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)


alt.Chart(...)

### 9. Assess Model Performance

In [406]:
from sklearn.metrics import classification_report, confusion_matrix, precision_score, f1_score

**Accuracy, precision and f1 scores on default model**

In [407]:
y_train_preds = random_search_et.predict(X_train)
y_val_preds = random_search_et.predict(X_val)
y_test_preds = random_search_et.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasatt

In [408]:


print("Accuracy Scores:")
print("On Training set:  ",accuracy_score(y_train, y_train_preds))
print("On Validation set:  ",accuracy_score(y_val, y_val_preds))
print("On Testing set:  ",accuracy_score(y_test, y_test_preds))

print("---------------")





Accuracy Scores:
On Training set:   0.9897560975609756
On Validation set:   0.9895311788802913
On Testing set:   0.9882577826324412
---------------


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

In [409]:


print("Precision Scores:")
print("On Training set:  ",precision_score(y_train, y_train_preds))
print("On Validation set:  ",precision_score(y_val, y_val_preds))
print("On Testing set:  ",precision_score(y_test, y_test_preds))

print("---------------")





Precision Scores:
On Training set:   0.0
On Validation set:   0.0
On Testing set:   0.0
---------------


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

In [410]:
print("f1 Scores:")
print("On Training set:  ",f1_score(y_train, y_train_preds))
print("On Validation set:  ",f1_score(y_val, y_val_preds))
print("On Testing set:  ",f1_score(y_test, y_test_preds))

print("---------------")

f1 Scores:
On Training set:   0.0
On Validation set:   0.0
On Testing set:   0.0
---------------


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

In [411]:
print(confusion_matrix(y_test, y_test_preds))

[[3619    0]
 [  43    0]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

**Accuracy, precision and f1 scores for the best hyperparameters**

In [420]:
y_train_preds = et2.predict(X_train)
y_val_preds = et2.predict(X_val)
y_test_preds = et2.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasatt

In [421]:


print("Accuracy Scores:")
print("On Training set:  ",accuracy_score(y_train, y_train_preds))
print("On Validation set:  ",accuracy_score(y_val, y_val_preds))
print("On Testing set:  ",accuracy_score(y_test, y_test_preds))

print("---------------")





Accuracy Scores:
On Training set:   0.9897560975609756
On Validation set:   0.9895311788802913
On Testing set:   0.9882577826324412
---------------


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

In [422]:


print("Precision Scores:")
print("On Training set:  ",precision_score(y_train, y_train_preds))
print("On Validation set:  ",precision_score(y_val, y_val_preds))
print("On Testing set:  ",precision_score(y_test, y_test_preds))

print("---------------")





Precision Scores:
On Training set:   0.0
On Validation set:   0.0
On Testing set:   0.0
---------------


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

In [423]:
print("f1 Scores:")
print("On Training set:  ",f1_score(y_train, y_train_preds))
print("On Validation set:  ",f1_score(y_val, y_val_preds))
print("On Testing set:  ",f1_score(y_test, y_test_preds))

print("---------------")

f1 Scores:
On Training set:   0.0
On Validation set:   0.0
On Testing set:   0.0
---------------


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp

In [424]:
print(confusion_matrix(y_test, y_test_preds))

[[3619    0]
 [  43    0]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtyp